// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Night.Data;

#nullable disable

namespace Night.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604142533_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Night.Models.CollectiveEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DateLabel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("CollectiveEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateLabel = "Friday",
                            Description = "A monthly gamejam that anyone can join. New promt everytime!",
                            Location = "Online + local pop-up",
                            Title = "Monthly Gamejam"
                        },
                        new
                        {
                            Id = 2,
                            DateLabel = "Summer 2026",
                            Description = "A curated evening celebrating independent game creation, installations, talks, and live demos.",
                            Location = "Community gallery",
                            Title = "Games as Art Showcase"
                        });
                });

            modelBuilder.Entity("Night.Models.CollectiveMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.HasKey("Id");

                    b.ToTable("CollectiveMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "/images/collective-members/night-collective.jpg",
                            Name = "Night Collective",
                            Position = "Curators, developers, artists, and players",
                            Quote = "We champion small teams, expressive play, accessible tools, and games that belong in galleries as much as living rooms."
                        });
                });

            modelBuilder.Entity("Night.Models.CollectiveProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("CollectiveProjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creator = "Mira Sol",
                            Description = "A tiny exploration game about mapping memories, procedural stars, and unfinished conversations.",
                            Medium = "Interactive poem",
                            Title = "Dream Cartographers"
                        },
                        new
                        {
                            Id = 2,
                            Creator = "APT Studio",
                            Description = "A cabinet-scale exhibition that treats high scores, rituals, and glitches as community folklore.",
                            Medium = "Playable installation",
                            Title = "Arcade Reliquary"
                        },
                        new
                        {
                            Id = 3,
                            Creator = "Jun Vale",
                            Description = "A non-violent boss rush where every encounter is resolved through rhythm, dialogue, and care.",
                            Medium = "Experimental action game",
                            Title = "Soft Boss Rush"
                        });
                });

            modelBuilder.Entity("Night.Models.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Games are art.",
                            Name = "Night Collective",
                            Role = "Nightjar is a non-profit organization striving to be a democratic game publisher. To be precise, we are a local community of weird game makers who care deeply about the artistry of video games."
                        });
                });

            modelBuilder.Entity("Night.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CollectiveMemberId")
                        .HasColumnType("int");

                    b.Property<string>("DeveloperPublisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FromCollective")
                        .HasColumnType("bit");

                    b.Property<int>("GenreGameplayType")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Platforms")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CollectiveMemberId");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("Night.Models.Game", b =>
                {
                    b.HasOne("Night.Models.CollectiveMember", null)
                        .WithMany("Games")
                        .HasForeignKey("CollectiveMemberId");
                });

            modelBuilder.Entity("Night.Models.CollectiveMember", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
